import Foundation

// MARK: - PATH-directory executable shims
//
// PINNED DECISION #1: shims are EXECUTABLE wrapper scripts in `~/.sesame/shims/`,
// NOT shell functions. Agents run commands in non-interactive/non-login shells
// that never source `~/.zshrc` / `~/.bashrc`, so a shell-function shim would
// silently never fire; a PATH-directory shim always intercepts.
//
// PINNED DECISION #2 (no recursion): each shim execs the wrapped binary's REAL
// ABSOLUTE path, resolved at install time with `~/.sesame/shims` excluded from
// the search — so `npm` in the shim never re-hits the shim.

public enum Shims {
    /// The marker every generated shim carries in its header, so uninstall only
    /// ever removes files Sesame wrote — never an unrelated binary on PATH.
    /// Interpolated verbatim into `render` (see below); keep the two in sync.
    public static let generatedMarker = "generated by `sesame shim install`"

    /// `~/.sesame/shims` — the directory the user prepends to PATH.
    public static func dir() -> URL {
        dir(home: URL(fileURLWithPath: NSHomeDirectory()))
    }

    /// The shims dir under an EXPLICIT home — so callers (and tests) can point it
    /// at a hermetic temp home instead of the process's real `$HOME`.
    public static func dir(home: URL) -> URL {
        home.appendingPathComponent(".sesame").appendingPathComponent("shims")
    }

    /// Resolve a command's REAL absolute path by scanning `path` (a `:`-joined
    /// PATH string) while SKIPPING `excludeDir` (the shims dir) — so we never
    /// bake the shim's own path in. Returns the first executable match, or nil.
    public static func resolveRealBinary(_ name: String, path: String,
                                         excluding excludeDir: String) -> String? {
        let fm = FileManager.default
        let exclude = URL(fileURLWithPath: excludeDir).standardizedFileURL.path
        for entry in path.components(separatedBy: ":") {
            if entry.isEmpty { continue }
            if URL(fileURLWithPath: entry).standardizedFileURL.path == exclude { continue }
            let candidate = URL(fileURLWithPath: entry).appendingPathComponent(name).path
            var isDir: ObjCBool = false
            if fm.fileExists(atPath: candidate, isDirectory: &isDir),
               !isDir.boolValue, fm.isExecutableFile(atPath: candidate) {
                return candidate
            }
        }
        return nil
    }

    /// The exact bytes of a generated shim. `sesamePath` and `realPath` are baked
    /// in as absolute paths. At run time the shim delegates to `sesame shim-exec`,
    /// which reads the nearest `.sesame`, injects only the ABSENT mapped secrets
    /// (env-present ones are skipped → no prompt), then execs `realPath`.
    public static func render(name: String, realPath: String, sesamePath: String) -> String {
        let sesameQ = shellDoubleQuote(sesamePath)
        let realQ = shellDoubleQuote(realPath)
        let nameQ = shellDoubleQuote(name)
        return """
        #!/bin/sh
        # sesame shim for `\(name)` — \(generatedMarker). Do not edit.
        # Remove with: sesame shim uninstall
        #
        # At run time this asks Sesame (via the nearest .sesame) which secrets this
        # invocation of `\(name)` needs, injects only the ones NOT already in the env
        # (each behind Touch ID), then execs the real binary below by its absolute
        # path — so there is no recursion back into this shim.
        exec \(sesameQ) shim-exec --name \(nameQ) --real \(realQ) -- "$@"

        """
    }

    /// Write executable shims for `names` into `shimsDir`, resolving each command's
    /// REAL binary on `path` (with `shimsDir` excluded, so no recursion) and baking
    /// in `sesamePath` (the absolute path to the real `sesame` CLI). A command not
    /// on PATH or that fails to write is SKIPPED with a reason — never fatal. Shared
    /// by the CLI (`shim install`, `open`) and the app's one-click enable, so the
    /// shim-authoring logic lives in exactly one place.
    public static func install(_ names: [String], into shimsDir: URL,
                               sesamePath: String, path: String)
        -> (installed: [String], skipped: [(name: String, reason: String)]) {
        var installed: [String] = []
        var skipped: [(name: String, reason: String)] = []
        for name in names {
            guard let real = resolveRealBinary(name, path: path, excluding: shimsDir.path) else {
                skipped.append((name, "not found on PATH"))
                continue
            }
            let script = render(name: name, realPath: real, sesamePath: sesamePath)
            let file = shimsDir.appendingPathComponent(name)
            do {
                try script.write(to: file, atomically: true, encoding: .utf8)
                try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: file.path)
            } catch {
                skipped.append((name, "write failed: \(error.localizedDescription)"))
                continue
            }
            installed.append(name)
        }
        return (installed, skipped)
    }

    /// Remove Sesame-generated shims from `dir` — ONLY files carrying
    /// `generatedMarker`, so an unrelated binary in the dir is never touched. Pass
    /// `only` to limit removal to those names; nil removes every generated shim.
    /// Returns the names removed. Shared by `shim uninstall` and the app's off path.
    @discardableResult
    public static func uninstallGenerated(from dir: URL, only names: Set<String>? = nil) -> [String] {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(atPath: dir.path) else { return [] }
        var removed: [String] = []
        for name in entries {
            if let names = names, !names.contains(name) { continue }
            let file = dir.appendingPathComponent(name)
            let contents = (try? String(contentsOf: file, encoding: .utf8)) ?? ""
            guard contents.contains(generatedMarker) else { continue }
            if (try? fm.removeItem(at: file)) != nil { removed.append(name) }
        }
        return removed
    }

    /// How many Sesame-generated shims currently live in `dir` (marker-matched).
    public static func countGenerated(in dir: URL) -> Int {
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(atPath: dir.path) else { return 0 }
        return entries.reduce(into: 0) { count, name in
            let contents = (try? String(contentsOf: dir.appendingPathComponent(name), encoding: .utf8)) ?? ""
            if contents.contains(generatedMarker) { count += 1 }
        }
    }

    /// Double-quote a string for POSIX sh, escaping `\`, `"`, `$`, and backtick.
    static func shellDoubleQuote(_ s: String) -> String {
        var out = "\""
        for ch in s {
            if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" {
                out.append("\\")
            }
            out.append(ch)
        }
        out.append("\"")
        return out
    }
}
