import Foundation

// MARK: - PATH-directory executable shims
//
// PINNED DECISION #1: shims are EXECUTABLE wrapper scripts in `~/.sesame/shims/`,
// NOT shell functions. Agents run commands in non-interactive/non-login shells
// that never source `~/.zshrc` / `~/.bashrc`, so a shell-function shim would
// silently never fire; a PATH-directory shim always intercepts.
//
// PINNED DECISION #2 (no recursion): each shim execs the wrapped binary's REAL
// ABSOLUTE path, resolved at install time with `~/.sesame/shims` excluded from
// the search — so `npm` in the shim never re-hits the shim.

public enum Shims {
    /// `~/.sesame/shims` — the directory the user prepends to PATH.
    public static func dir() -> URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent(".sesame")
            .appendingPathComponent("shims")
    }

    /// Resolve a command's REAL absolute path by scanning `path` (a `:`-joined
    /// PATH string) while SKIPPING `excludeDir` (the shims dir) — so we never
    /// bake the shim's own path in. Returns the first executable match, or nil.
    public static func resolveRealBinary(_ name: String, path: String,
                                         excluding excludeDir: String) -> String? {
        let fm = FileManager.default
        let exclude = URL(fileURLWithPath: excludeDir).standardizedFileURL.path
        for entry in path.components(separatedBy: ":") {
            if entry.isEmpty { continue }
            if URL(fileURLWithPath: entry).standardizedFileURL.path == exclude { continue }
            let candidate = URL(fileURLWithPath: entry).appendingPathComponent(name).path
            var isDir: ObjCBool = false
            if fm.fileExists(atPath: candidate, isDirectory: &isDir),
               !isDir.boolValue, fm.isExecutableFile(atPath: candidate) {
                return candidate
            }
        }
        return nil
    }

    /// The exact bytes of a generated shim. `sesamePath` and `realPath` are baked
    /// in as absolute paths. At run time the shim delegates to `sesame shim-exec`,
    /// which reads the nearest `.sesame`, injects only the ABSENT mapped secrets
    /// (env-present ones are skipped → no prompt), then execs `realPath`.
    public static func render(name: String, realPath: String, sesamePath: String) -> String {
        let sesameQ = shellDoubleQuote(sesamePath)
        let realQ = shellDoubleQuote(realPath)
        let nameQ = shellDoubleQuote(name)
        return """
        #!/bin/sh
        # sesame shim for `\(name)` — generated by `sesame shim install`. Do not edit.
        # Remove with: sesame shim uninstall
        #
        # At run time this asks Sesame (via the nearest .sesame) which secrets this
        # invocation of `\(name)` needs, injects only the ones NOT already in the env
        # (each behind Touch ID), then execs the real binary below by its absolute
        # path — so there is no recursion back into this shim.
        exec \(sesameQ) shim-exec --name \(nameQ) --real \(realQ) -- "$@"

        """
    }

    /// Double-quote a string for POSIX sh, escaping `\`, `"`, `$`, and backtick.
    static func shellDoubleQuote(_ s: String) -> String {
        var out = "\""
        for ch in s {
            if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" {
                out.append("\\")
            }
            out.append(ch)
        }
        out.append("\"")
        return out
    }
}
